"""add_table_chapter

Revision ID: c7d5cd6a9c61
Revises: b2daf665d67c
Create Date: 2023-06-23 00:45:17.184526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d5cd6a9c61'
down_revision = 'b2daf665d67c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('comix_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['comix_id'], ['comix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_id'), 'chapter', ['id'], unique=False)
    op.create_index(op.f('ix_chapter_title'), 'chapter', ['title'], unique=False)
    op.alter_column('comix', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comix', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_chapter_title'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_id'), table_name='chapter')
    op.drop_table('chapter')
    # ### end Alembic commands ###
